import type { AppProps } from 'next/app';
import Head from 'next/head';

import { Fragment } from 'react';

import GlobalStyles from '@/styles/global';

import 'antd/dist/antd.css';

function MyApp({ Component, pageProps }: AppProps) {
  const getLayout = Component.getLayout || ((page) => page);

  return (
    <Fragment>
      <Head>
        <title>Admin Ingress</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <GlobalStyles />

      {getLayout(<Component {...pageProps} />)}
    </Fragment>
  );
}

export default MyApp;
