import type { AppProps } from 'next/app';
import Head from 'next/head';

import { Fragment, useEffect, useState } from 'react';

import GlobalStyles from '@/styles/global';

import 'antd/dist/antd.css';

function MyApp({ Component, pageProps }: AppProps) {
  const getLayout = Component.getLayout || ((page) => page);
  const [showChild, setShowChild] = useState(false);

  useEffect(() => {
    setShowChild(true);
  }, []);

  if (!showChild) return null;

  return (
    <Fragment>
      <Head>
        <title>Admin Ingress</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <GlobalStyles />

      {getLayout(<Component {...pageProps} />)}
    </Fragment>
  );
}

export default MyApp;
