import type { AppProps } from 'next/app';
import Head from 'next/head';
import { useRouter } from 'next/router';

import { useEffect, useState } from 'react';

import client from '@/apollo/client';
import GlobalStyles from '@/styles/global';
import { ApolloProvider } from '@apollo/client';

import 'antd/dist/antd.css';

import { useAtom } from 'jotai';

import { tokenAtom } from './login';
import Login from './login';

function MyApp({ Component, pageProps }: AppProps) {
  const getLayout = Component.getLayout || ((page) => page);
  const [showChild, setShowChild] = useState(false);
  const router = useRouter();
  const [token] = useAtom(tokenAtom);

  useEffect(() => {
    setShowChild(true);
  }, []);

  useEffect(() => {
    if (!token) return router.push('/login');
  }, [token]);

  if (!showChild) return null;

  return (
    <ApolloProvider client={client}>
      <Head>
        <title>Admin Ingress</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <GlobalStyles />
      {token ? getLayout(<Component {...pageProps} />) : <Login />}
    </ApolloProvider>
  );
}

export default MyApp;
